version: "3.3"

services:
  web:
    stdin_open: true
    tty: true
    # 根据Dockerfile生成镜像文件
    build: .
    image: nginx-gunicorn-flask:latest
    # 挂载代码到容器对应目录
    volumes:
      - ./flaskr:/project/flaskai/flaskr
      - ./instance:/project/flaskai/instance
      - ./run.py:/project/flaskai/run.py
      - ./nginx.conf:/etc/nginx/sites-available/nginx.conf
      - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    # 主机与容器端口映射
    ports:
      - "80:80"
    command: "/usr/bin/supervisord"
